/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogos;

import javax.swing.JOptionPane;

/**
 *
 * @author MINEIRO
 */
public class TelaTresChances extends javax.swing.JFrame {
    private int numSort = 0, vidas, chute;
    private boolean acertou;
    
    /**
     * Creates new form TelaTresChances
     */
    public TelaTresChances() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNum = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        lblMensagem = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenu();
        menuTelaInicial = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo das Três Chances");

        lblNum.setText("Digite o número:");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        lblMensagem.setText("Mensagem:");

        txtMensagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        menuAjuda.setText("Ajuda");
        menuAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAjudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAjuda);

        menuSobre.setText("Sobre");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSobre);

        menuTelaInicial.setText("Tela Inicial");
        menuTelaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTelaInicialMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTelaInicial);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        //====================
        MetodosGerais inst = new MetodosGerais();
        numSort = inst.sorteiaNum(1, 10);
        txtMensagem.setText("Número sorteado entre 1 a 10, tente adivinhar!");
        
        acertou = false;
        vidas = 3;
        //====================
    }//GEN-LAST:event_btnIniciarActionPerformed
    
    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        //=================
        try {
            boolean valida;
            
            chute = Integer.parseInt(txtNum.getText());
            valida = validaJogo();
            if(valida){
                vidas--;
                if (chute == numSort){
                    JOptionPane.showMessageDialog(null, "Parabéns! Missão Cumprida!");
                    acertou = true;
                    numSort = 0; // reseta a variável do número sorteado
                } else if(vidas > 0){
                    txtMensagem.setText("Tente outra vez, você ainda tem "+ vidas +" vidas");
                } else {
                    JOptionPane.showMessageDialog(null, "Game Over!");
                    txtMensagem.setText("O número sorteado é: "+ numSort);
                }    
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Número inválido, digite novamente");
        }    
        //=================
    }//GEN-LAST:event_txtNumActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        //=================
        JOptionPane.showMessageDialog(null, "Joguinho bem simples desenvolvido por Luiz Felipe.");
        //=================
    }//GEN-LAST:event_menuSobreMouseClicked

    private void menuTelaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTelaInicialMouseClicked
        //=================
        new TelaInicial().setVisible(true);
        this.dispose();
        //=================
    }//GEN-LAST:event_menuTelaInicialMouseClicked

    private void menuAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAjudaMouseClicked
        //=================
        JOptionPane.showMessageDialog(null, "Neste jogo é sorteado um número entre 1 e 10; \n"
                + "Seu objetivo acertar este número para que possa 'sobreviver'; \n"
                + "Você possui 3 vidas e a cada erro uma dessas vidas é retirada; \n"
                + "Caso não acerte com essas 3 chances, YOU LOSE!!! \n");
        //=================
    }//GEN-LAST:event_menuAjudaMouseClicked
    
    private boolean validaJogo(){
        boolean situacao = true;
        
        if(chute > 10 || chute < 1){
            JOptionPane.showMessageDialog(null, "O número tem que estar entre 1 e 10!");
            situacao = false;
        } else if(numSort == 0){
            JOptionPane.showMessageDialog(null, "Para começar clique no botão Iniciar!");
            situacao = false;
        } else if(acertou || vidas == 0){
            JOptionPane.showMessageDialog(null, "Está rodada já acabou, clique em Iniciar para jogar novamente!");
            situacao = false;
        }
        return situacao;
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTresChances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTresChances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTresChances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTresChances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTresChances().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNum;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenu menuTelaInicial;
    private javax.swing.JLabel txtMensagem;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
